export const SIGN_UP_USER_REQUEST = 'SIGN_UP_USER_REQUEST';
export const SIGN_UP_USER_FAILURE = 'SIGN_UP_USER_FAILURE';
export const SIGN_UP_USER_SUCCESS = 'SIGN_UP_USER_SUCCESS';

export const SIGN_IN_USER_REQUEST = 'SIGN_IN_USER_REQUEST';
export const SIGN_IN_USER_FAILURE = 'SIGN_IN_USER_FAILURE';
export const SIGN_IN_USER_SUCCESS = 'SIGN_IN_USER_SUCCESS';
