export const GET_MEETUPS_REQUEST = 'GET_MEETUPS_REQUEST';
export const GET_MEETUPS_SUCCESS = 'GET_MEETUPS_SUCCESS';
export const GET_MEETUPS_FAILURE = 'GET_MEETUPS_FAILURE';

export const SEARCH_MEETUPS_REQUEST = 'SEARCH_MEETUPS_REQUEST';
export const SEARCH_MEETUPS_SUCCESS = 'SEARCH_MEETUPS_SUCCESS';
export const SEARCH_MEETUPS_FAILURE = 'SEARCH_MEETUPS_FAILURE';

