export const GET_MEETUP_PAGE_NAV_ITEMS = 'GET_MEETUP_PAGE_NAV_ITEMS'
export const GET_LOGIN_PAGE_ITEMS = 'GET_LOGIN_PAGE_ITEMS'
export const GET_SIGNUP_PAGE_ITEMS = 'GET_SIGNUP_PAGE_ITEMS'
export const GET_ALL_ROOT_PAGE_NAV_ITEMS = 'GET_ALL_ROOT_PAGE_NAV_ITEMS'

export const pageToActionType = {
    login: GET_LOGIN_PAGE_ITEMS,
    signup: GET_SIGNUP_PAGE_ITEMS,
    meetupList: GET_MEETUP_PAGE_NAV_ITEMS,
    '': GET_ALL_ROOT_PAGE_NAV_ITEMS,
}
